name: "Publish"
on:
  push:
    branches:
      - main
jobs:
  publish:

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - uses: cachix/install-nix-action@v30

      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true

      - run: |
          set -x +e
          hugo --minify 2>&1 | tee hugo.output

      - run: "git add --force docs/ hugo.output"
      # --force ignores the .gitignore

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: always()
        with:
          commit_message: "Build ${{ github.sha }}"
          branch: built
          create_branch: true
          push_options: --force
